# Generated by Django 4.0 on 2022-08-20 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('ngo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngo',
            name='staff',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
    ]
